### ISSUE TITLE
Server-side rendering issue with Angular Universal

### ISSUE THREAD

**Issue by Adrian-Ghita** [dibari/angular-ellipsis#90]
Angular version: 9.1.4 (Ivy enabled)

When running in SSR mode (on 2.2.2 version), an error is thrown (only on server-side render):
`TypeError: this.removeWindowResizeListener is not a function`

It worked fine on v2.1.2.
